### ISSUE TITLE
Exception when using Star in Version Number

### ISSUE THREAD

**Issue by larrybud2004** [Virtuoze/NuPack#8]
When defining an assembly version, you can have Visual Studio set the build and revision numbers by using the '*', such as:

[assembly: AssemblyVersion("1.0.*")]

When doing so, NuPack fails with an exception:

Unhandled Exception: System.ComponentModel.DataAnnotations.ValidationException: Version is required.
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.Save(Stream stream, Boolean validate, Int32 minimumManifestVersion)
   at NuGet.PackageBuilder.WriteManifest(Package package, Int32 minimumManifestVersion)
   at NuGet.PackageBuilder.Save(Stream stream)
   at NuCreate.Program.Save(String directory, PackageBuilder package)
   at NuCreate.Program.Create(String solution, String project, String configuration, String plateform, String assembly)
   at NuCreate.Program.Main(String[] arguments)

**Comment by larrybud2004** [comment]
Correction, the error occurs because there was no **AssemblyFileVersion** defined.
