### ISSUE TITLE
Unhandled Exception when using .nuspec

### ISSUE THREAD

**Issue by tsvetelin-pavlov** [Virtuoze/NuPack#9]
Whenever I try to build a project with .nuspec, I get this: 

`Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Sources\TeamProjectDir\Sources\DEV\SolutionDir\ProjectDirProperties\TheNuspecFile.nuspec'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuCreate.Program.Open(String filename)
   at NuCreate.Program.Create(String solution, String project, String configuration, String plateform, String assembly)
   at NuCreate.Program.Main(String[] arguments)`

The problem, as far as I can see it is that it doesn't put slash between Properties and the file (the correct path is 'D:\Sources\TeamProjectDir\Sources\DEV\SolutionDir\ProjectDir\Properties\TheNuspecFile.nuspec').

I usually put my .nuspec files in Properties folder in order to have nicely organized project, but I've checked - there is no difference if the .nuspec is in the project dir, and no difference if the .nuspec is named with more simpler name (i.e. Package.nuspec) - the issue remains.

**Comment by larrybud2004** [comment]
I have the same issue.  Sounds like this project has been abandoned.

**Comment by jlchavez** [comment]
Have you tried to pull the code and compile it?

I had the same problem, there hasn't been any update to the nuget.org site, but I  have changed a couple of things until today, to mix minor issues. In September 2017, it was merged to this repository that change.
